version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:1.3.0
    ports:
      - "127.0.0.1:5001:5001"
    volumes:
      - "./docker/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./docker/localstack/s3:/s3"
      - "./docker/localstack/kms/seed.yaml:/init/seed.yaml"
    environment:
      - EDGE_PORT=5001
      - KMS_PROVIDER=local-kms
    healthcheck:
      test: awslocal s3api wait bucket-exists --bucket test-core-bucket
        && awslocal s3api wait bucket-exists --bucket test-optout-bucket
      interval: 5s
      timeout: 5s
      retries: 3

  core:
    container_name: core
    image: ghcr.io/iabtechlab/uid2-core:<CORE_VERSION>
    ports:
      - "127.0.0.1:8088:8088"
    volumes:
      - ./docker/uid2-core/conf/local-e2e-docker-config.json:/app/conf/local-config.json
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      test: wget --tries=1 --spider http://localhost:8088/ops/healthcheck || exit 1
      interval: 5s
      timeout: 5s
      retries: 10

  optout:
    container_name: optout
    image: ghcr.io/iabtechlab/uid2-optout:<OPTOUT_VERSION>
    ports:
      - "127.0.0.1:8090:8081"
      - "127.0.0.1:5090:5005"
    volumes:
      - ./docker/uid2-optout/conf/local-e2e-docker-config.json:/app/conf/local-config.json
      - ./docker/uid2-optout/mount/:/opt/uid2/optout/
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8081/ops/healthcheck" ]
      interval: 5s

  publicoperator:
    container_name: public_operator
    image: ghcr.io/iabtechlab/uid2-operator:<OPERATOR_VERSION>
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9080:9080"
      - "127.0.0.1:5080:5005"
    volumes:
      - ../conf/local-e2e-docker-public-config.json:/app/conf/local-config.json
    depends_on:
      core:
        condition: service_healthy
      optout:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/ops/healthcheck" ]
      interval: 5s

  e2etest:
    container_name: e2e_test
    image: ghcr.io/iabtechlab/uid2-e2e:<E2E_VERSION>
    depends_on:
      core:
        condition: service_healthy
      publicoperator:
        condition: service_healthy
